#!/bin/bash
# Ensures the necessary build tools are installed and then builds tuplex.
# This script is in the repo and can be run directly:  tuplex/compiler/scripts/txinstall

set -x  # command echo on

###################
## Install the packages with the build tools and LLVM needed to build the tuplex compiler:

sudo apt update
sudo apt install -y bison cmake make gcc g++ libllvm11 llvm-11-dev

# Note: Check http://apt.llvm.org/ in case of issues or for other Linux flavors


###################
## Build the Tuplex compiler:

# Add LLVM 11 to the command path:
# (To make this permament for all bash sessions, it can be appended to ~/.bashrc or similar file.)
export PATH=$PATH:/usr/lib/llvm-11/bin

# cd to the compiler's directory:
cd tuplex/compiler

# create a build directory (for out-of-source building):
mkdir -p build-release
cd build-release

# build it:
cmake ..
make -j9  # recommended value: number of CPU cores + 1


###################
## Add Tuplex paths and set Tuplex env vars:
# (These assume pwd is the build directory)
# (To make this permament for all bash sessions, it can be appended to ~/.bashrc or similar file.)

export TUPLEX_HOME=$PWD/..
export PATH=$PATH:$TUPLEX_HOME/scripts
export PATH=$PATH:$PWD/bin
