#!/bin/bash

if [ -n "$TUPLEX_HOME" ]; then
    HOME_DIR="$TUPLEX_HOME"
elif [ -f "./autotest/test.py" ]; then
    HOME_DIR=.
elif [ -f "../autotest/test.py" ]; then
    HOME_DIR=..
else
    echo "Could not find the Tuplex root directory: " $HOME_DIR
    echo "Is the current directory not a build directory?"
    exit 1
fi
echo "Found the Tuplex home directory: " $HOME_DIR

if [ -f "$TUPLEX_HOME/bin/txc" ]; then
    export TXCBIN=$TUPLEX_HOME/bin/txc
elif [ -f "./bin/txc" ]; then
    export TXCBIN=`pwd`/bin/txc
fi
if [ -f "$TXCBIN" ]; then
    echo "Found the txc binary: " $TXCBIN
else
    echo "Could not find the txc binary: " $TXCBIN
    exit 1
fi

python3 $HOME_DIR/autotest/test.py
